import type { NextPage } from 'next'
import Head from 'next/head'
import css from './ig.module.scss'

import Image from 'next/image'
import Logo from '../public/images/logo.png';
import Sparkles from '../public/images/sparkles.png'

import Button from '../components/Button/Button';

const Ig: NextPage = () => {
    return (
        <div className={css.container}>
          <Head>
            <title>Hashtag Awesome Nails</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className={css.main}>
            <div className={css.logoContainer}>
            <Image
                src={Logo} 
                alt="Hashtag Awesome Nails logo" 
                width="400px"
                height="400px"
                className={css.logo} />
            </div>
            <div className={css.buttonsContainer}>
                <Button>
                    Nail Prompts
                </Button>
                <div className={css.comingSoonWrapper}>
                <div className={css.sparkles}>
                    <Image
                    src={Sparkles} 
                    alt="" 
                    width="48px"
                    height="48px" />
                </div>
                <p className={css.comingSoon}>Coming soon</p>
                <div className={css.sparkles}>
                    <Image
                    src={Sparkles} 
                    alt="" 
                    width="48px"
                    height="48px" />
                </div>
                </div>
                <a href="https://www.instagram.com/hashtag.awesome.nails/" target="_blank" rel="noreferrer">
                    <Button className={css.igButton}>
                        Instagram
                    </Button>
                </a>
                <a href="https://www.pinterest.com.au/hashtagawesomenails/" target="_blank" rel="noreferrer">
                    <Button className={css.igButton}>
                        Pinterest
                    </Button>
                </a>
            </div>
          </main>
        </div>
    )
}

export default Ig
