import type { NextPage } from 'next'
import Head from 'next/head'
import css from './index.module.scss'

import Image from 'next/image'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faShuffle } from '@fortawesome/free-solid-svg-icons'
import { library } from '@fortawesome/fontawesome-svg-core'

import Logo from '../public/images/logo.png';

library.add(faShuffle);

const Home: NextPage = () => {
  return (
    <div className={css.container}>
      <Head>
        <title>Hashtag Awesome Nails</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={css.main}>
        <div className={css.logoContainer}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <Image
            src={Logo} 
            alt="Hashtag Awesome Nails logo" 
            width="400px"
            height="400px"
            className={css.logo} />
        </div>
        <h1 className={css.centerText}>Coming Soon!</h1>
      </main>
    </div>
  )
}

export default Home
